<!--Intro Section-->
    <section class="subscribe-intro">
    	<div class="auto-container">
        	<div class="row clearfix">
            	<!--Column-->
                <div class="column col-md-9 col-sm-12 col-xs-12">
                	<h2>Subcribe for Newsletter</h2>
                    There are many variations of passages of Lorem Ipsum available but the majority have 
                </div>
                <!--Column-->
                <div class="column col-md-3 col-sm-12 col-xs-12">
                	<div class="text-right padd-top-20">
                		<a href="#" class="theme-btn btn-style-three">Subscribe Now</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
	
    
    <!--Main Footer-->
    <footer class="main-footer" style="background-image:url(<?php echo $root; ?>assets/images/background/footer-bg.jpg);">
    	
        <!--Footer Upper-->        
        <div class="footer-upper">
            <div class="auto-container">
                <div class="row clearfix">
                	
                    <!--Two 4th column-->
                    <div class="col-md-6 col-sm-12 col-xs-12">
                    	<div class="row clearfix">
                            <div class="col-lg-8 col-sm-6 col-xs-12 column">
                                <div class="footer-widget about-widget">
                                    <div class="logo"><a href="<?php echo $root; ?>Home"><img src="<?php echo $root; ?>assets/images/project_logo.png" class="img-responsive" alt=""></a></div>
                                    <div class="text">
                                        <p id="des">Lorem ipsum dolor sit amet, eu me seo <br>laboramus, iudico dummy  text.</p>
                                    </div>
                                    
                                    <ul class="contact-info">
                                    	<li><span class="icon fa fa-map-marker"></span> 60 Grant Ave. Carteret NJ 0708</li>
                                        <li><span class="icon fa fa-phone"></span> (880) 1723801729</li>
                                        <li><span class="icon fa fa-envelope-o"></span> example@gmail.com</li>
                                    </ul>
                                    
                                    <div class="social-links-two clearfix">
                                    	<a href="#" class="facebook img-circle"><span class="fa fa-facebook-f"></span></a>
                                        <a href="#" class="twitter img-circle"><span class="fa fa-twitter"></span></a>
                                        <a href="#" class="google-plus img-circle"><span class="fa fa-google-plus"></span></a>
                                        <a href="#" class="linkedin img-circle"><span class="fa fa-pinterest-p"></span></a>
                                        <a href="#" class="linkedin img-circle"><span class="fa fa-linkedin"></span></a>
                                    </div>
                                    
                                </div>
                            </div>
                            
                            <!--Footer Column-->
                            <div class="col-lg-4 col-sm-6 col-xs-12 column">
                                <h2>Our Project</h2>
                                <div class="footer-widget links-widget">
                                    <ul>
                                        <li><a href="#">Water Surve</a></li>
                                        <li><a href="#">Education for all</a></li>
                                        <li><a href="#">Treatment</a></li>
                                        <li><a href="#">Food Serving</a></li>
                                        <li><a href="#">Cloth</a></li>
                                        <li><a href="#">Selter Project</a></li>
                                        <li><a href="#">Help Orphan</a></li>
                                    </ul>
        
                                </div>
                            </div>
                    	</div>
                    </div><!--Two 4th column End-->
                    
                    <!--Two 4th column-->
                    <div class="col-md-6 col-sm-12 col-xs-12">
                    	<div class="row clearfix">
                    		<!--Footer Column-->
                        	<div class="col-lg-7 col-sm-6 col-xs-12 column">
                            	<div class="footer-widget news-widget">
                                	<h2>Latest News</h2>	
                                    <div class="news-post">
                                    	<div class="icon"></div>
                                        <div class="news-content"><a href="#">If you need a crown or lorem an implant you will pay it gap it</a></div>
                                        <div class="time">July 2, 2014</div>
                                    </div>
                                    
                                    <div class="news-post">
                                    	<div class="icon"></div>
                                        <div class="news-content"><a href="#">If you need a crown or lorem an implant you will pay it gap it</a></div>
                                        <div class="time">July 2, 2014</div>
                                    </div>
                                    
                                    <div class="news-post">
                                    	<div class="icon"></div>
                                        <div class="news-content"><a href="#">If you need a crown or lorem an implant you will pay it gap it</a></div>
                                        <div class="time">July 2, 2014</div>
                                    </div>
                                    
                                </div>
                            </div>
                            
                            <!--Footer Column-->
                            <div class="col-lg-5 col-sm-6 col-xs-12 column">
                                <div class="footer-widget links-widget">
                                	<h2>Quick Links</h2>
                                    <ul>
                                        <li><a href="#">Water Surve</a></li>
                                        <li><a href="#">Education for all</a></li>
                                        <li><a href="#">Treatment</a></li>
                                        <li><a href="#">Food Serving</a></li>
                                        <li><a href="#">Cloth</a></li>
                                        <li><a href="#">Selter Project</a></li>
                                        <li><a href="#">Help Orphan</a></li>
                                    </ul>
        
                                </div>
                            </div>
                    	</div>
                    </div><!--Two 4th column End-->
                    
                </div>
                
            </div>
        </div>
        
        <!--Footer Bottom-->
    	<div class="footer-bottom">
            <div class="auto-container clearfix">
                <!--Copyright-->
                <div class="copyright text-center">Copyright 2016 &copy; Designed by <a href="http://therightsol.com/">TR Solutions</a></div>
            </div>
        </div>
        
    </footer>    
    
</div>
<!--End pagewrapper-->


<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target=".main-header"><span class="fa fa-arrow-up"></span></div>

<script src="<?php echo $root; ?>assets/js/jquery.js"></script> 
<script src="<?php echo $root; ?>assets/js/bootstrap.min.js"></script>
<script src="<?php echo $root; ?>assets/js/revolution.min.js"></script>
<script src="<?php echo $root; ?>assets/js/jquery.appear.js"></script>
<script src="<?php echo $root; ?>assets/js/knob.js"></script>
<script src="<?php echo $root; ?>assets/js/jquery.fancybox.pack.js"></script>
<script src="<?php echo $root; ?>assets/js/jquery.fancybox-media.js"></script>
<script src="<?php echo $root; ?>assets/js/validate.js"></script>
<script src="<?php echo $root; ?>assets/js/wow.js"></script>
<script src="<?php echo $root; ?>assets/js/script.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>assets/js/picedit.min.js"></script>
<script>
    $.ajax({
        url: "<?php echo $root; ?>generals",
        dataType: 'json',
        cache:true,
        success: function(result){
            var logo = result[0]['company_logo_header'];
            $('.logo img').attr('src', logo);
            $('#header_mail').attr('href', 'mailto:'+result[0]['contact_email_header']).html(result[0]['contact_email_header']);
            $('.facebook').attr('href',result[0]['facebook_url_header']);
            $('.twitter').attr('href',result[0]['twitter_url_header']);
            $('.google-plus').attr('href',result[0]['gplus_url_header']);
            $('.linkedin').attr('href',result[0]['linkedin_url_header']);
            $('#com_address').html(result[0]['company_address']);
            $('#com_phone').html(result[0]['company_phone1']+', '+result[0]['company_phone2']+', '+result[0]['company_phone3']);
            $('#com_mail').html(result[0]['company_email_1']+', '+result[0]['company_email_2']);
            $('#des').html(result[0]['company_short_description']);
    }});
</script>

</body>
 
</html>
