<!DOCTYPE html>
<?php $root = base_url(); ?>
<html>
<head>
<meta charset="utf-8">
<title>Save a Soul | Project</title>
<!-- Stylesheets -->
<link href="<?php echo $root; ?>assets/css/bootstrap.css" rel="stylesheet">
<link href="<?php echo $root; ?>assets/css/style.css" rel="stylesheet">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="<?php echo $root; ?>assets/fonts/flaticon.eot">
<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link href="<?php echo $root; ?>assets/css/responsive.css" rel="stylesheet">
<link href="<?php echo $root; ?>assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo $root; ?>assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo $root; ?>assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
<link rel="shortcut icon" href="favicon.ico"><!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/plugins/select2/select2_metro.css">
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME STYLES -->
<link href="<?php echo $root; ?>assets/css/style-metronic.css" rel="stylesheet" type="text/css">
<link href="<?php echo $root; ?>assets/css/style.css" rel="stylesheet" type="text/css">
<link href="<?php echo $root; ?>assets/css/style-responsive.css" rel="stylesheet" type="text/css">
<link href="<?php echo $root; ?>assets/css/plugins.css" rel="stylesheet" type="text/css">
<link href="<?php echo $root; ?>assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color">
<link href="<?php echo $root; ?>assets/css/custom.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/picedit.min.css" />
    <link href="<?php echo $root; ?>admin_assets/css/xeditable.min.css" rel="stylesheet">
    <link href="<?php echo $root; ?>assets/css/revolution-slider.css" rel="stylesheet">

<!-- END THEME STYLES -->

</head>