<!-- END COPYRIGHT -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="<?php echo $root; ?>admin_assets/plugins/respond.min.js"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/excanvas.min.js"></script>
<![endif]-->
<script src="<?php echo $root; ?>admin_assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/data-tables/DT_bootstrap.js"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/select2/select2.min.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $root; ?>admin_assets/scripts/table-ajax.js"></script>
<script src="<?php echo $root; ?>admin_assets/scripts/table-editable.js"></script>
<script src="<?php echo $root; ?>admin_assets/scripts/app.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/scripts/login.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/scripts/table-editable.js"></script>

<!-- Mirrored from www.keenthemes.com/preview/metronic_admin/login.html by HTTrack Website Copier/3.x [XR&CO'2013], Wed, 18 Dec 2013 10:45:26 GMT -->
</html>