<!-- END COPYRIGHT -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="<?php echo $root; ?>admin_assets/plugins/respond.min.js"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/excanvas.min.js"></script>
<![endif]-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $root; ?>admin_assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/data-tables/DT_bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/jquery-validation/dist/additional-methods.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>
<script src="<?php echo $root; ?>admin_assets/scripts/form-wizard.js"></script>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $root; ?>admin_assets/scripts/app.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/scripts/login.js" type="text/javascript"></script>
<script src="<?php echo $root; ?>admin_assets/scripts/table-advanced.js"></script>
<script src="<?php echo $root; ?>admin_assets/scripts/custom.js"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script src="<?php echo $root; ?>admin_assets/scripts/xeditable.min.js" type="text/javascript"></script>
<!-- END BODY -->
<link href="<?php echo $root; ?>admin_assets/css/xeditable.min.css" rel="stylesheet">


<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/froala_editor.min.js"></script>

<!-- Include Code Mirror. -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js"></script>

<!-- Include Plugins. -->
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/align.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/char_counter.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/code_beautifier.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/code_view.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/colors.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/emoticons.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/entities.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/file.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/font_family.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/font_size.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/fullscreen.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/image.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/image_manager.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/inline_style.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/line_breaker.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/link.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/lists.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/paragraph_format.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/paragraph_style.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/quick_insert.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/quote.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/table.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/save.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/url.min.js"></script>
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/plugins/video.min.js"></script>

<!-- Include Language file if we want to use it. -->
<script type="text/javascript" src="<?php echo $root; ?>admin_assets/plugins/froala/js/languages/ro.js"></script>

<script type="text/javascript" src="<?php echo $root; ?>assets/js/picedit.min.js"></script>
<script src="https://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.0.2/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.0.2/js/responsive.bootstrap.min.js"></script>



<!-- Mirrored from www.keenthemes.com/preview/metronic_admin/login.html by HTTrack Website Copier/3.x [XR&CO'2013], Wed, 18 Dec 2013 10:45:26 GMT -->
</html>