<!DOCTYPE html>
<?php $root = base_url(); ?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8"/>
    <title>My Elaaj | Admin Dashboard</title>
    <title>My Elaaj | Admin Dashboard</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <meta name="MobileOptimized" content="320">
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="<?php echo $root; ?>admin_assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>admin_assets/plugins/select2/select2_metro.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css"/>
    <!-- END PAGE LEVEL SCRIPTS -->
    <!-- BEGIN THEME STYLES -->
    <link href="<?php echo $root; ?>admin_assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
    <link href="<?php echo $root; ?>admin_assets/css/pages/login.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/custom.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/plugins/froala/css/froala_editor.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $root; ?>admin_assets/plugins/froala/css/froala_style.min.css" rel="stylesheet" type="text/css" />

    <!-- Include Code Mirror style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">

    <!-- Include Editor Plugins style. -->
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/char_counter.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/code_view.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/colors.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/emoticons.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/file.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/fullscreen.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/image.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/image_manager.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/line_breaker.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/quick_insert.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/table.css">
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/froala/css/plugins/video.css">
    <!-- END THEME STYLES -->
    <link href="<?php echo $root; ?>admin_assets/css/xeditable.min.css" rel="stylesheet">
    <link href="<?php echo $root; ?>admin_assets/css/prettyPhoto.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/picedit.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.0.2/css/responsive.bootstrap.min.css">

    <link href="<?php echo $root; ?>assets/dropzon/dropzone.css" rel="stylesheet">




</head>