<!DOCTYPE html>
<?php $root = base_url(); ?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<!-- Mirrored from www.keenthemes.com/preview/metronic_admin/login.html by HTTrack Website Copier/3.x [XR&CO'2013], Wed, 18 Dec 2013 10:45:19 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8"/>
    <title>Save a soul | Admin Dashboard Template</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <meta name="MobileOptimized" content="320">
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="<?php echo $root; ?>admin_assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="<?php echo $root; ?>admin_assets/plugins/data-tables/DT_bootstrap.css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>admin_assets/plugins/select2/select2_metro.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>admin_assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css"/>
    <!-- END PAGE LEVEL SCRIPTS -->
    <!-- BEGIN THEME STYLES -->
    <link href="<?php echo $root; ?>admin_assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
    <link href="<?php echo $root; ?>admin_assets/css/pages/login.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/custom.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $root; ?>admin_assets/css/pages/profile.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="<?php echo $root; ?>assets/favicon.ico"/>
</head>